import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const contentDir = path.join(__dirname, '../content/tracks');

interface LessonSeed {
  track: string;
  module: string;
  locale: 'en-US' | 'pt-BR';
  id: string;
  title: string;
  description: string;
  difficulty: number;
  skills: string[];
  mode: 'code' | 'prose';
  text: string;
  display: 'code' | 'prose';
  language?: string;
}

const seeds: LessonSeed[] = [
  // devops en-US
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'en-US',
    id: '001-docker-run',
    title: 'Docker Run',
    description: 'Practice typing docker run commands.',
    difficulty: 2,
    skills: ['docker', 'cli'],
    mode: 'code',
    text: 'docker run -d --name web -p 8080:80 nginx:latest',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'en-US',
    id: '002-docker-compose',
    title: 'Docker Compose',
    description: 'Type docker-compose service definitions.',
    difficulty: 2,
    skills: ['docker', 'yaml'],
    mode: 'code',
    text: 'docker compose up -d --build\ndocker compose logs -f api',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'en-US',
    id: '003-kubectl-get',
    title: 'Kubectl Get',
    description: 'Practice kubectl resource inspection commands.',
    difficulty: 2,
    skills: ['kubernetes', 'cli'],
    mode: 'code',
    text: 'kubectl get pods -n production -l app=api --watch',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'en-US',
    id: '004-terraform-plan',
    title: 'Terraform Plan',
    description: 'Type terraform workflow commands.',
    difficulty: 3,
    skills: ['terraform', 'iac'],
    mode: 'code',
    text: 'terraform init\nterraform plan -var-file=prod.tfvars',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'en-US',
    id: '005-shell-pipeline',
    title: 'Shell Pipeline',
    description: 'Practice DevOps shell pipelines.',
    difficulty: 2,
    skills: ['shell', 'pipes'],
    mode: 'code',
    text: 'curl -s https://api.example.com/health | jq .status',
    display: 'code',
    language: 'bash',
  },
  // devops pt-BR
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'pt-BR',
    id: '001-docker-run',
    title: 'Docker Run',
    description: 'Pratique digitar comandos docker run.',
    difficulty: 2,
    skills: ['docker', 'cli'],
    mode: 'code',
    text: 'docker run -d --name web -p 8080:80 nginx:latest',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'pt-BR',
    id: '002-docker-compose',
    title: 'Docker Compose',
    description: 'Digite definições de serviço docker-compose.',
    difficulty: 2,
    skills: ['docker', 'yaml'],
    mode: 'code',
    text: 'docker compose up -d --build\ndocker compose logs -f api',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'pt-BR',
    id: '003-kubectl-get',
    title: 'Kubectl Get',
    description: 'Pratique comandos kubectl de inspeção.',
    difficulty: 2,
    skills: ['kubernetes', 'cli'],
    mode: 'code',
    text: 'kubectl get pods -n production -l app=api --watch',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'pt-BR',
    id: '004-terraform-plan',
    title: 'Terraform Plan',
    description: 'Digite comandos do fluxo terraform.',
    difficulty: 3,
    skills: ['terraform', 'iac'],
    mode: 'code',
    text: 'terraform init\nterraform plan -var-file=prod.tfvars',
    display: 'code',
    language: 'bash',
  },
  {
    track: 'devops',
    module: 'docker-cli',
    locale: 'pt-BR',
    id: '005-shell-pipeline',
    title: 'Pipeline Shell',
    description: 'Pratique pipelines shell em DevOps.',
    difficulty: 2,
    skills: ['shell', 'pipes'],
    mode: 'code',
    text: 'curl -s https://api.example.com/health | jq .status',
    display: 'code',
    language: 'bash',
  },
  // data-science en-US
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'en-US',
    id: '001-pandas-read',
    title: 'Pandas Read CSV',
    description: 'Type pandas data loading snippets.',
    difficulty: 2,
    skills: ['pandas', 'python'],
    mode: 'code',
    text: "import pandas as pd\ndf = pd.read_csv('data.csv', parse_dates=['created_at'])",
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'en-US',
    id: '002-sql-select',
    title: 'SQL Select',
    description: 'Practice SQL aggregation queries.',
    difficulty: 2,
    skills: ['sql', 'analytics'],
    mode: 'code',
    text: 'SELECT user_id, COUNT(*) AS events\nFROM analytics.events\nGROUP BY user_id;',
    display: 'code',
    language: 'sql',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'en-US',
    id: '003-list-comprehension',
    title: 'List Comprehension',
    description: 'Type Python list comprehensions.',
    difficulty: 2,
    skills: ['python', 'comprehensions'],
    mode: 'code',
    text: 'values = [x * 2 for x in range(10) if x % 2 == 0]',
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'en-US',
    id: '004-numpy-array',
    title: 'NumPy Array',
    description: 'Practice NumPy array creation.',
    difficulty: 2,
    skills: ['numpy', 'python'],
    mode: 'code',
    text: 'import numpy as np\narr = np.array([[1, 2], [3, 4]], dtype=float)',
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'en-US',
    id: '005-matplotlib-plot',
    title: 'Matplotlib Plot',
    description: 'Type matplotlib plotting code.',
    difficulty: 3,
    skills: ['matplotlib', 'visualization'],
    mode: 'code',
    text: "import matplotlib.pyplot as plt\nplt.plot(x, y, label='trend')\nplt.legend()",
    display: 'code',
    language: 'python',
  },
  // data-science pt-BR
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'pt-BR',
    id: '001-pandas-read',
    title: 'Pandas Read CSV',
    description: 'Digite snippets de carregamento com pandas.',
    difficulty: 2,
    skills: ['pandas', 'python'],
    mode: 'code',
    text: "import pandas as pd\ndf = pd.read_csv('dados.csv', parse_dates=['criado_em'])",
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'pt-BR',
    id: '002-sql-select',
    title: 'SQL Select',
    description: 'Pratique consultas SQL com agregação.',
    difficulty: 2,
    skills: ['sql', 'analytics'],
    mode: 'code',
    text: 'SELECT usuario_id, COUNT(*) AS eventos\nFROM analytics.eventos\nGROUP BY usuario_id;',
    display: 'code',
    language: 'sql',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'pt-BR',
    id: '003-list-comprehension',
    title: 'List Comprehension',
    description: 'Digite list comprehensions em Python.',
    difficulty: 2,
    skills: ['python', 'comprehensions'],
    mode: 'code',
    text: 'valores = [x * 2 for x in range(10) if x % 2 == 0]',
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'pt-BR',
    id: '004-numpy-array',
    title: 'NumPy Array',
    description: 'Pratique criação de arrays NumPy.',
    difficulty: 2,
    skills: ['numpy', 'python'],
    mode: 'code',
    text: 'import numpy as np\narr = np.array([[1, 2], [3, 4]], dtype=float)',
    display: 'code',
    language: 'python',
  },
  {
    track: 'data-science',
    module: 'python-sql',
    locale: 'pt-BR',
    id: '005-matplotlib-plot',
    title: 'Matplotlib Plot',
    description: 'Digite código de plotagem matplotlib.',
    difficulty: 3,
    skills: ['matplotlib', 'visualization'],
    mode: 'code',
    text: "import matplotlib.pyplot as plt\nplt.plot(x, y, label='tendencia')\nplt.legend()",
    display: 'code',
    language: 'python',
  },
  // legal-translators en-US
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'en-US',
    id: '001-contract-clause',
    title: 'Contract Clause',
    description: 'Type standard contract limitation clauses.',
    difficulty: 3,
    skills: ['legal', 'contracts'],
    mode: 'prose',
    text: 'The parties agree that liability shall be limited to direct damages arising from material breach of this agreement.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'en-US',
    id: '002-privacy-term',
    title: 'Privacy Term',
    description: 'Practice privacy policy vocabulary.',
    difficulty: 2,
    skills: ['legal', 'privacy'],
    mode: 'prose',
    text: 'Personal data shall be processed lawfully, fairly, and in a transparent manner in relation to the data subject.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'en-US',
    id: '003-notary-term',
    title: 'Notary Term',
    description: 'Type notarial and registry terminology.',
    difficulty: 3,
    skills: ['legal', 'notary'],
    mode: 'prose',
    text: 'The notary public certifies that the signatory appeared in person and acknowledged execution of the instrument.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'en-US',
    id: '004-litigation-term',
    title: 'Litigation Term',
    description: 'Practice litigation and court vocabulary.',
    difficulty: 3,
    skills: ['legal', 'litigation'],
    mode: 'prose',
    text: 'Plaintiff moves this Court for summary judgment on the grounds that no genuine dispute of material fact exists.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'en-US',
    id: '005-ip-term',
    title: 'IP Term',
    description: 'Type intellectual property terminology.',
    difficulty: 2,
    skills: ['legal', 'ip'],
    mode: 'prose',
    text: 'Licensee shall not sublicense, assign, or transfer any rights granted under this intellectual property agreement.',
    display: 'prose',
  },
  // legal-translators pt-BR
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'pt-BR',
    id: '001-clausula-contrato',
    title: 'Cláusula Contratual',
    description: 'Digite cláusulas padrão de limitação de responsabilidade.',
    difficulty: 3,
    skills: ['legal', 'contracts'],
    mode: 'prose',
    text: 'As partes concordam que a responsabilidade será limitada a danos diretos decorrentes de violação material deste contrato.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'pt-BR',
    id: '002-termo-privacidade',
    title: 'Termo de Privacidade',
    description: 'Pratique vocabulário de política de privacidade.',
    difficulty: 2,
    skills: ['legal', 'privacy'],
    mode: 'prose',
    text: 'Os dados pessoais serão tratados de forma lícita, leal e transparente em relação ao titular dos dados.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'pt-BR',
    id: '003-termo-cartorio',
    title: 'Termo Cartorário',
    description: 'Digite terminologia notarial e registral.',
    difficulty: 3,
    skills: ['legal', 'notary'],
    mode: 'prose',
    text: 'O tabelião certifica que o signatário compareceu pessoalmente e reconheceu a execução do instrumento.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'pt-BR',
    id: '004-termo-litigio',
    title: 'Termo de Litígio',
    description: 'Pratique vocabulário processual e forense.',
    difficulty: 3,
    skills: ['legal', 'litigation'],
    mode: 'prose',
    text: 'O autor requer julgamento antecipado sob o fundamento de inexistência de controvérsia sobre fato relevante.',
    display: 'prose',
  },
  {
    track: 'legal-translators',
    module: 'legal-terms',
    locale: 'pt-BR',
    id: '005-termo-pi',
    title: 'Termo de PI',
    description: 'Digite terminologia de propriedade intelectual.',
    difficulty: 2,
    skills: ['legal', 'ip'],
    mode: 'prose',
    text: 'O licenciado não poderá sublicenciar, ceder ou transferir quaisquer direitos concedidos neste acordo de propriedade intelectual.',
    display: 'prose',
  },
];

async function main() {
  for (const seed of seeds) {
    const dir = path.join(contentDir, seed.track, seed.locale, seed.module);
    await mkdir(dir, { recursive: true });

    const lesson = {
      id: seed.id,
      module: seed.module,
      track: seed.track,
      locale: seed.locale,
      title: seed.title,
      description: seed.description,
      difficulty: seed.difficulty,
      estimatedMinutes: 2,
      skills: seed.skills,
      mode: seed.mode,
      content: {
        text: seed.text,
        display: seed.display,
        ...(seed.language ? { language: seed.language } : {}),
      },
      goals: { minAccuracy: 90 },
      author: 'coderkeys-team',
      source: null,
      version: 1,
    };

    const filePath = path.join(dir, `${seed.id}.json`);
    await writeFile(filePath, `${JSON.stringify(lesson, null, 2)}\n`);
  }

  console.log(`✓ Generated ${seeds.length} lessons`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
